{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T03:10:42.743Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T03:11:46.101Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T03:13:18.340Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T03:33:12.976Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T03:37:40.564Z"}
{"level":"error","message":"Unable to connect to the database: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at new BaseError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at Client.eval (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:149:20)\n    at Connection.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/client.js:144:18)\n    at Object.onceWrapper (node:events:30:7970)\n    at Connection.emit (node:events:30:10899)\n    at Socket.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/connection.js:62:12)\n    at Socket.emit (node:events:30:10899)\n    at <anonymous> (node:net:285:3666)\n    at <anonymous> (https://sb1xgdnhd-1wap.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199560)","timestamp":"2024-12-05T04:15:07.409Z"}
{"level":"error","message":"Unable to connect to the database: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at new BaseError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at Client.eval (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:149:20)\n    at Connection.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/client.js:144:18)\n    at Object.onceWrapper (node:events:30:7970)\n    at Connection.emit (node:events:30:10899)\n    at Socket.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/connection.js:62:12)\n    at Socket.emit (node:events:30:10899)\n    at <anonymous> (node:net:285:3666)\n    at <anonymous> (https://sb1xgdnhd-1wap.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199560)","timestamp":"2024-12-05T04:16:27.164Z"}
{"level":"error","message":"Unable to connect to the database: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at new BaseError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at Client.eval (/home/projects/sb1-xgdnhd/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:149:20)\n    at Connection.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/client.js:144:18)\n    at Object.onceWrapper (node:events:30:7970)\n    at Connection.emit (node:events:30:10899)\n    at Socket.eval (/home/projects/sb1-xgdnhd/node_modules/pg/lib/connection.js:62:12)\n    at Socket.emit (node:events:30:10899)\n    at <anonymous> (node:net:285:3666)\n    at <anonymous> (https://sb1xgdnhd-1wap.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199560)","timestamp":"2024-12-05T04:16:37.484Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-my3n7hmv.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T04:33:04.592Z"}
{"level":"error","message":"Unable to connect to the database: connect ECONNREFUSED 127.0.0.1:5432","name":"SequelizeConnectionRefusedError","original":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"parent":{"address":"127.0.0.1","code":"ECONNREFUSED","errno":-61,"port":5432,"syscall":"connect"},"stack":"SequelizeConnectionRefusedError: connect ECONNREFUSED 127.0.0.1:5432\n    at new BaseError (/home/project/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/project/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at new ConnectionRefusedError (/home/project/node_modules/sequelize/lib/errors/connection/connection-refused-error.js:30:5)\n    at Client.eval (/home/project/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:133:24)\n    at Client._handleErrorWhileConnecting (/home/project/node_modules/pg/lib/client.js:326:19)\n    at Client._handleErrorEvent (/home/project/node_modules/pg/lib/client.js:336:19)\n    at Connection.emit (node:events:30:10899)\n    at Socket.reportStreamError (/home/project/node_modules/pg/lib/connection.js:57:12)\n    at Socket.emit (node:events:30:10899)\n    at emitErrorNT (node:internal/streams/destroy:215:1091)\n    at emitErrorCloseNT (node:internal/streams/destroy:215:746)\n    at processTicksAndRejections (node:internal/process/task_queues:192:1067)\n    at <anonymous> (https://zp1v56uxy8rdx5ypatb0ockcb9tr6a-oci3-my3n7hmv.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199593)","timestamp":"2024-12-05T04:33:29.567Z"}
{"level":"error","message":"Unable to connect to the database: Connection terminated unexpectedly","name":"SequelizeConnectionError","original":{},"parent":{},"stack":"SequelizeConnectionError: Connection terminated unexpectedly\n    at new BaseError (/home/projects/sb1-tmteax/node_modules/sequelize/lib/errors/base-error.js:13:5)\n    at new ConnectionError (/home/projects/sb1-tmteax/node_modules/sequelize/lib/errors/connection-error.js:35:5)\n    at Client.eval (/home/projects/sb1-tmteax/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:149:20)\n    at Connection.eval (/home/projects/sb1-tmteax/node_modules/pg/lib/client.js:144:18)\n    at Object.onceWrapper (node:events:30:7970)\n    at Connection.emit (node:events:30:10899)\n    at Socket.eval (/home/projects/sb1-tmteax/node_modules/pg/lib/connection.js:62:12)\n    at Socket.emit (node:events:30:10899)\n    at <anonymous> (node:net:285:3666)\n    at <anonymous> (https://sb1tmteax-ynav.w-credentialless-staticblitz.com/blitz.fc837ba8.js:40:199560)","timestamp":"2024-12-05T04:34:52.583Z"}
